### ISSUE TITLE
Do this project support customize model and datasets?

### ISSUE THREAD

**Issue by Elissa0723** [jlko/semantic_uncertainty#1]
Hi, could this project support customize model and datasets?
If possible, could give some example and the support format for customize datasets?
Thanks a lot!

**Comment by jlko** [comment]
Hi Elissa,

Thanks for your interest in the semantic entropy!

`uncertainty/models/huggingface_models.py` and `uncertainty/data/data_utils.py` should give you a pretty good idea for how to add additional models and datasets!
Let me know if you struggle with anything concretely!

Cheers
Jannik

**Comment by Elissa0723** [comment]
> Hi Elissa,
> 
> Thanks for your interest in the semantic entropy!
> 
> `uncertainty/models/huggingface_models.py` and `uncertainty/data/data_utils.py` should give you a pretty good idea for how to add additional models and datasets! Let me know if you struggle with anything concretely!
> 
> Cheers Jannik

thanks so lot!
