### ISSUE TITLE
Calculating entropy with/without normalization

### ISSUE THREAD

**Issue by manhitv** [jlko/semantic_uncertainty#10]
Thanks for sharing your script.

I have a couple of questions about calculating entropy as follows.
1. I think naive entropy should be calculated like this:

```
p_si = np.exp(log_liks_agg) / np.sum(np.exp(log_liks_agg))
naive_entropy = -np.sum(p_si * np.log(p_si))
```

Why you use MC estimation instead?

2. When calculating probability over each cluster with the same semantic ids, could we simply remove the shifting components (i.e. np.log(np.sum(np.exp(log_likelihoods))) and simply does as follows.

`log_likelihood_per_semantic_id = np.log(np.sum(np.exp(id_log_likelihoods)))`

What role does the shifting component play in the calculation process?
Also similar to question 1, after getting `log_likelihood_per_semantic_id`, should we normalize them before calculating semantic entropy?

```
p_si_semantic = np.exp(log_likelihood_per_semantic_id) / np.sum(np.exp(log_likelihood_per_semantic_id))
semantic_entropy = -np.sum(p_si_semantic * np.log(p_si_semantic))
```

Thank you in advance!

**Comment by jlko** [comment]
Hi Manh,

Thanks for your interest in the codebase and apologies for the delayed reply. A lot has been going on these last weeks!

1. We believe Monte Carlo estimation is the correct thing to do here. The entropy $H(x)=E_{p(x)}[-\log p(x)]$ can be estimated as $H(x) \approx\frac{1}{M}\sum_{i=1}^M (- \log p(x_i))$ with samples $x_i\sim p(x)$. Including $p(x_i)$ in the sum would be probabilistically wrong in our case where $x_i$ are samples from the distribution. However, the estimator that you suggest can be used for some discrete settings where the expectation can be evaluated analytically, $E_{p(x)}[-\log p(x)]=\sum_{x\in\mathcal{X}} p(x) \log p(x)$, but this requires summing over all possible values of $x$ – which is not the setting we find ourselves in here as summing over all possible sequences generated by the model is intractable.

2. We have found empirically that normalizing cluster probabilities (by the total probability mass over all clusters) leads to better performance than naive summing. For our discrete semantic entropy estimator, we then further do compute the rao-blackwellized (what you call normalized) estimator as our estimate of the entire cluster probability distribution allows for this. We discuss this a bit more in the methods section of the [paper](https://www.nature.com/articles/s41586-024-07421-0#MOESM1) ('Computing Semantic Entropy').

I hope this helped and feel free to send an e-mail if you have any further questions! As your questions are more related to the paper than the code base, I'm going to go ahead and close this issue.

Cheers
Jannik

**Comment by manhitv** [comment]
Thank you for your informative response. It helped me a lot in understanding your paper more deeply.
