### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by woqv2023** [jlko/semantic_uncertainty#2]
Sorry to bother you, but could you please clarify whether you used a subset of the dataset or the entire dataset for your experiments? I noticed that the nq_open dataset alone has 88,000 entries in the test set, which might be very time-consuming to process.

**Comment by jlko** [comment]
We use a subset:

> For each dataset, we use 400 train examples and 400 test examples randomly sampled from the original larger dataset. [...]

This will also be enabled in the code by default. Please see the methods section of the paper for more details!

**Comment by woqv2023** [comment]
thanks for your reply

**Comment by jlko** [comment]
No worries at all and thanks for your interest in our project!
