### ISSUE TITLE
How to compute AUROC for semantic entropy?

### ISSUE THREAD

**Issue by xansar** [jlko/semantic_uncertainty#4]
As far as I understand, the input y_pred for calculating AUROC should be probabilities between 0 and 1. However, it seems that the library directly uses semantic entropy as y_pred, and semantic entropy can be greater than 1. How does the code handle this issue?

**Comment by jlko** [comment]
Hi Xansar,

Thanks for your interest in the codebase!

> As far as I understand, the input y_pred for calculating AUROC should be probabilities between 0 and 1.

I believe this is incorrect, see documentation for `y_score` here https://scikit-learn.org/stable/modules/generated/sklearn.metrics.roc_curve.html:

> Target scores, can either be probability estimates of the positive class, confidence values, or __non-thresholded measure of decisions__ (as returned by “decision_function” on some classifiers). [emphasis mine]

It should thus be fine to use `roc_curve` with semantic entropies.

Let me know if you have any further concerns here!

Cheers
Jannik

**Comment by 421zuoduan** [comment]
> As far as I understand, the input y_pred for calculating AUROC should be probabilities between 0 and 1. However, it seems that the library directly uses semantic entropy as y_pred, and semantic entropy can be greater than 1. How does the code handle this issue?

hi there, i am wondering the right way to get AUROC. Could you plz tell me how AUROC is calculated?

**Comment by jlko** [comment]
Hi 421zuoduan,

I'm happy to help. AUROC is calculated with https://scikit-learn.org/stable/modules/generated/sklearn.metrics.roc_curve.html.

If you have another question, feel free to open a new issue or each out to us via e-mail.

Cheers
Jannik
