### ISSUE TITLE
Issue with determining the number of generated tokens

### ISSUE THREAD

**Issue by AIchberger** [jlko/semantic_uncertainty#6]
Hi Jannik,

In `semantic_uncertainty/uncertainty/models/huggingface_models.py`, the method of determining the number of generated tokens by tokenizing the already decoded full answer does not always yield correct results:

`token_stop_index = self.tokenizer(full_answer[:input_data_offset + stop_at], return_tensors="pt")['input_ids'].shape[1]`

The following example from TriviaQA shows that despite two tokens being generated, the number of generated tokens is incorrectly calculated as one, since the tokenizer encodes the answer differently than how it was generated by the model:
- full answer:  `What major river flows through Paris? \n Answer: seine`
- original tokens for generated answer "seine": `[409, 457]`
- newly encoded token for generated answer "seine": `[6676]`

In this example, the discrepancy affects the likelihood of the generated sequence, as only the first token’s likelihood is taken into account. Additionally, an ablation study on including the stop token when generating the likelihood might be insightful. Although this might not significantly change your overall results, I wanted to bring it to your attention.

Best,
Lukas

**Comment by jlko** [comment]
Hi Lukas,

Thanks for bringing this to our attention. I'd love to dig deeper into this but this will likely have to wait until after the NeurIPS rebuttals.

Until then, some questions:

1. Our code calls the tokenizer twice. First on `input_data` and then on `full_answer[:input_data_offset + stop_at]`. I would expect these variables to be the following:
* `input data='Question: What major river flows through Paris?\nAnswer:'` 
* `full_answer='Question: What major river flows through Paris?\nAnswer: seine\n'`  (or similar)
* `full_answer[:input_data_offset + stop_at]='Question: What major river flows through Paris?\nAnswer: seine'` (i.e. just removing the stop_token)

I'm guessing this all works as intended?

You're saying that the model generates 'seine' as two tokens initially but then our retokenization of `full_answer[:input_data_offset + stop_at]` leads to a single-token `seine`?

I agree this would lead to inconsistencies, although I would hope that these are quite rare. (I've done fairly extensive manual testing of this function.)

You've thought about this a bit (and I haven't thought about this in a long-ish time): Do you have any good ideas for how to fix this?

2. In your example, is full answer missing the `Question:` and prompt/few-shot examples? (This should not affect functionality but just curious where this input is coming from.)

3. As for including the stop tokens, I would expect this to not improve performance. For some models, it will likely not change performance (e.g. if the model always confidently terminates predictions using `</s>`), while for other models it may degrade performance (if the model is inconsistently uncertain over how to terminate predictions, e.g. with `</s>` or `\n` or `\n\n` tokens.)

Thanks for your help! 
Best wishes
Jannik

**Comment by AIchberger** [comment]
Hi Jannik,

1. You are right that removing the stop token works as intended. However, I suggest avoiding decoding the generated text and instead directly working with the encoded tokens. Since the token IDs of all stop tokens are known, we can directly remove the first occurrence of a stop token and everything generated after it. Similarly, the tokens of the encoded prompt are known. The prompt always ends with `\nAnswer:`, which is encoded as `[13, 22550, 29901]`. Thus, we can search for the last occurrence of this token ID combination to determine the length of the input prompt.

2. The full answer actually includes the few-shot prompt as well. But for simplicity, I only copied the actual question and answer.

3. That makes sense. However, I assume that the probability of the stop token might also convey information about the certainty of terminating the prediction. For instance, a model might be uncertain about generating `seine</s>` versus `seine and danube</s>`. In this example, it could be valuable to include the probability of generating the stop token.

I performed initial tests comparing the current implementation of determining the number of generated tokens with my above-described approach, which operates on the encoded answer and includes the stop token probability. The results with `Llama-2-7b-chat` are comparable. The mean AUROC increased by about 0.6% for regular entropy and by about 0.2% for semantic entropy, suggesting only a small impact on final performance.

Best,
Lukas

**Comment by jlko** [comment]
Hi Lukas,

Apologies for my delay in replying – it's been busy days and I hope this was not too urgent.

1. Re: "The prompt always ends with \nAnswer:, which is encoded as [13, 22550, 29901]". Interesting that this token sequence always appears in all encoded prompts. I'm not sure if we can actually rely on this! But it looks like this version is more reliable than the current algorithm anyways.

2. Gotcha!

3. It would be interesting to look into this. LMK if I can support you in doing so.

> I performed initial tests comparing the current implementation of determining the number of generated tokens with my above-described approach, which operates on the encoded answer and includes the stop token probability. The results with Llama-2-7b-chat are comparable. The mean AUROC increased by about 0.6% for regular entropy and by about 0.2% for semantic entropy, suggesting only a small impact on final performance.

This is definitely within variance! Regardless, thanks a lot for running these. If you'd like to submit a PR that adds your algorithm as an option (I'd like to keep the OG one for reproducibility reasons), that would be perfect!

Cheers
Jannik
