### ISSUE TITLE
What are the changes in this repo compared to semantic entropy computed in previous repo?

### ISSUE THREAD

**Issue by itsmemala** [jlko/semantic_uncertainty#7]
Hi,

Could you list the changes made to the semantic entropy computation in this repo, along with the reason for change, compared to the previous implementation in https://github.com/lorenzkuhn/semantic_uncertainty?

Thanks

**Comment by jlko** [comment]
Hi itsmemala,

Thanks a lot for your interest in our codebase.

The version of the code you link to is used in Kuhn et al. – if you want to exactly reproduce their experiments, this is the version to go to. However, that repo is not deprecated, and we would caution against using it for practical purposes. Please just use the code here instead whenever you can.

Unfortunately, I do not have a comprehensive list of the changes between the repos.

There's a few obvious changes such as the list of supported models and datasets, support for GPT models to estimate accuracy / entailment, the short/long generation settings. Then, as described in Farquhar et al., we've slightly changed the computation of semantic entropy as well as introduced a discrete semantic entropy estimator – both outperform the estimator suggested in Kuhn et al. in our experiments. 

Hope that helps!
